# Imports

import =["~/.config/alacritty/catppuccin-mocha.toml"]

# Font options

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

# Window options 

[window]
startup_mode = "Fullscreen"
# opacity = 0.6

[window.padding]
x = 10
y = 10

# Color options

[env]
TERM = "xterm-256color"
